wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9842798978054536
gamma:
  value: 0.99
hidden_size:
  value: 64
learning_rate:
  value: 6.807686857005182e-05
n_steps:
  value: 1024
seed:
  value: 1
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.7
