wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 0.9541427852992902
gamma:
  value: 0.98
hidden_size:
  value: 64
learning_rate:
  value: 2.3317932037245177e-05
n_steps:
  value: 1024
seed:
  value: 1
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.3
