wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 0.9470021130767128
gamma:
  value: 0.98
hidden_size:
  value: 64
learning_rate:
  value: 4.714021791910244e-05
n_steps:
  value: 2048
seed:
  value: 3
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.5
