wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9604491448856995
gamma:
  value: 0.98
hidden_size:
  value: 64
learning_rate:
  value: 0.0005265734140635382
n_steps:
  value: 2048
seed:
  value: 3
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.3
