wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 0.9543061543123142
gamma:
  value: 0.995
hidden_size:
  value: 128
learning_rate:
  value: 1.9800205819200628e-05
n_steps:
  value: 4096
seed:
  value: 4
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.3
