wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.965349436556306
gamma:
  value: 0.98
hidden_size:
  value: 128
learning_rate:
  value: 1.2750225625931665e-05
n_steps:
  value: 1024
seed:
  value: 1
total_timesteps:
  value: 1500000
vf_coef:
  value: 0.7
